dist: xenial

language: go
go:
  - "1.12.x"

go_import_path: github.com/arvancloud/redins

git:
  depth: 1

branches:
  only:
  - master

before_install:
  - apt-get install redis-server
  - echo "127.0.0.1 redis" >> /etc/hosts
  - mkdir -p $GOPATH/src/arvancloud/
  - ln -sf `pwd` $GOPATH/src/arvancloud/redins
  - cd $GOPATH/src/arvancloud/redins
